
spring:
  datasource:
    url: jdbc:mysql://114.202.33.83:3306/unknown?serverTimezone=UTC&characterEncoding=UTF-8
    username: dev
    password: ' !dev2024@'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: #
