spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weaver?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 'ckdwns4028'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: #
